### PR TITLE
Update Swags.md

### PR DESCRIPTION
**Pull request by namanjoshi19**
you can earn goodies by coding in codechef and redeem amaon pay e gift card

### CODE REVIEW

**Comment by DevMukhtarr** [comment]
Can you fix the URL so it can redirect users like others?

**Review by namanjoshi19 — COMMENTED** [review]
done

**Comment by namanjoshi19** [comment]
> Can you fix the URL so it can redirect users like others?

done now see

**Comment by DevMukhtarr** [comment]
[CODECHEF GOODIES](https://goodies.codechef.com/goodies/%e2%82%b9200-amazon-pay-egift-card/) - In Indian culture, nothing depicts sweetness better than a Laddu. Be it a birthday party, a wedding celebration, or an examination result, Laddu is the first thing you will get to lay your hands on,, you can code .. develop your coding practise and also earn goodies like amazon pay gift card by this .. Once you collect enough Laddus, you can then redeem them to get yourself anything from a wide range of CodeChef goodies.

**Comment by DevMukhtarr** [comment]
> [CODECHEF GOODIES](https://goodies.codechef.com/goodies/%e2%82%b9200-amazon-pay-egift-card/) - In Indian culture, nothing depicts sweetness better than a Laddu. Be it a birthday party, a wedding celebration, or an examination result, Laddu is the first thing you will get to lay your hands on,, you can code .. develop your coding practise and also earn goodies like amazon pay gift card by this .. Once you collect enough Laddus, you can then redeem them to get yourself anything from a wide range of CodeChef goodies.

Something like this above

**Comment by namanjoshi19** [comment]
> [CODECHEF GOODIES](https://goodies.codechef.com/goodies/%e2%82%b9200-amazon-pay-egift-card/) - In Indian culture, nothing depicts sweetness better than a Laddu. Be it a birthday party, a wedding celebration, or an examination result, Laddu is the first thing you will get to lay your hands on,, you can code .. develop your coding practise and also earn goodies like amazon pay gift card by this .. Once you collect enough Laddus, you can then redeem them to get yourself anything from a wide range of CodeChef goodies.

what are you doing why you copy pasting my idea

**Comment by DevMukhtarr** [comment]
> > [CODECHEF GOODIES](https://goodies.codechef.com/goodies/%e2%82%b9200-amazon-pay-egift-card/) - In Indian culture, nothing depicts sweetness better than a Laddu. Be it a birthday party, a wedding celebration, or an examination result, Laddu is the first thing you will get to lay your hands on,, you can code .. develop your coding practise and also earn goodies like amazon pay gift card by this .. Once you collect enough Laddus, you can then redeem them to get yourself anything from a wide range of CodeChef goodies.
> 
> what are you doing why you copy pasting my idea

Kindly Go through The Markdown file to see how to add Url and description so you can fix your mistake
the list is in this format [LinkName](Link) : Description

**Review by DevMukhtarr — APPROVED** [review]

**Comment by MrKrishnaAgarwal** [comment]
@namanjoshi19 This branch is having merge conflicts, please resolve them.

No reply under 24hrs leads to closed PR.

Thanks

**Review by MrKrishnaAgarwal — CHANGES_REQUESTED** [review]
Please resolve the merged conflicts manually, thankyou

**Pull request closed without merging**
