### PR TITLE
added more events

### PR DESCRIPTION
**Pull request by akshitagupta15june**
@MrKrishnaAgarwal please review

### CODE REVIEW

**Review by MrKrishnaAgarwal — APPROVED** [review]
Amazing work 💯
Thanks a lot 👌

**Comment by akshitagupta15june** [comment]
should  i resolve the conflict

**Comment by MrKrishnaAgarwal** [comment]
> should i resolve the conflict

Yes please do that

**Comment by MrKrishnaAgarwal** [comment]
Why did you close the PR?

**Comment by akshitagupta15june** [comment]
now check!

**Comment by akshitagupta15june** [comment]
Thanks!

**Comment by MrKrishnaAgarwal** [comment]
Now its fine
Congrats 🎉

**Pull request merged**
