### PR TITLE
Added contributors image in readme

### LINKED ISSUE #36: contributors image in readme file
image
like this

### PR DESCRIPTION
**Pull request by Ankurrawat-12**
closes #36 

image

### CODE REVIEW

**Review by MrKrishnaAgarwal — APPROVED** [review]
Looks good!
Thanks a lot @Beast71421

**Comment by MrKrishnaAgarwal** [comment]
Thank you for your contribution! Your pull request has been merged 🎉.

We will be sure to credit you and we have added you to our contributors list.

Keep Contributing to Hacktoberfest!

If you have any questions, feel free to ask me. I will be happy to help you. 😊

Happy Contributing! 🎉

Kind Regards,
Krishna Agarwal

**Comment by Ankurrawat-12** [comment]
is this repo EXCLUDED from hacktoberfest
image

**Comment by MrKrishnaAgarwal** [comment]
**You are a alt and spam account**
Also, you have been blocked from interacting in future.

Don't do this 🚧

**Pull request merged**
